var categoryId="categoriesMobile";

var level=0;

function generateCategories( level ){
    if (level == 0){
        document.getElementById(categoryId).insertAdjacentHTML("beforeend","<p onclick=\"collapse(\'booksCategory\')\" class=\"categoriesTitle\">Books +</p><div id=\"booksCategory\"><p onclick=\"window.open(\'page/categories/fiction.html\',\'_parent\')\">Fiction</p><p onclick=\"window.open(\'page/categories/nonfiction.html\',\'_parent\')\">Non-Fiction</p><p onclick=\"window.open(\'page/categories/children.html\',\'_parent\')\">Children</p><p onclick=\"window.open(\'page/categories/poetry.html\',\'_parent\')\">Poetry</p><p onclick=\"window.open(\'page/categories/translation.html\',\'_parent\')\">Translations</p></div><p onclick=\"collapse(\'aboutCategory\')\" class=\"categoriesTitle\">About Us +</p><div id=\"aboutCategory\"><p>About us</p><p>Work with us</p><p>Publish with us</p></div><p onclick=\"collapse(\'artCategory\')\" class=\"categoriesTitle\">Arts and Craft +</p><div id=\"artCategory\"><p>Arts</p><p>Craft</p></div><p class=\"categoriesTitle\" onclick=\"window.open(\'page/author.html\',\'_parent\')\">Authors</p><p class=\"categoriesTitle\" onclick=\"window.open(\'page/poster.html\',\'_parent\')\">Poster Kavita</p><p class=\"categoriesTitle\" onclick=\"window.open(\'page/blog.html\',\'_parent\')\">Blog</p><p class=\"categoriesTitle\" onclick=\"window.open(\'page/account.html\',\'_parent\')\">Account</p>");
    }

    else if (level == 1){
        document.getElementById(categoryId).insertAdjacentHTML("beforeend","<p onclick=\"collapse(\'booksCategory\')\" class=\"categoriesTitle\">Books +</p><div id=\"booksCategory\"><p onclick=\"window.open(\'categories/fiction.html\',\'_parent\')\">Fiction</p><p onclick=\"window.open(\'categories/nonfiction.html\',\'_parent\')\">Non-Fiction</p><p onclick=\"window.open(\'categories/children.html\',\'_parent\')\">Children</p><p onclick=\"window.open(\'categories/poetry.html\',\'_parent\')\">Poetry</p><p onclick=\"window.open(\'categories/translation.html\',\'_parent\')\">Translations</p></div><p onclick=\"collapse(\'aboutCategory\')\" class=\"categoriesTitle\">About Us +</p><div id=\"aboutCategory\"><p>About us</p><p>Work with us</p><p>Publish with us</p></div><p onclick=\"collapse(\'artCategory\')\" class=\"categoriesTitle\">Arts and Craft +</p><div id=\"artCategory\"><p>Arts</p><p>Craft</p></div><p class=\"categoriesTitle\" onclick=\"window.open(\'author.html\',\'_parent\')\">Authors</p><p class=\"categoriesTitle\" onclick=\"window.open(\'poster.html\',\'_parent\')\">Poster Kavita</p><p class=\"categoriesTitle\" onclick=\"window.open(\'blog.html\',\'_parent\')\">Blog</p><p class=\"categoriesTitle\" onclick=\"window.open(\'account.html\',\'_parent\')\">Account</p>");
    }

    else if (level == 2){
        document.getElementById(categoryId).insertAdjacentHTML("beforeend","<p onclick=\"collapse(\'booksCategory\')\" class=\"categoriesTitle\">Books +</p><div id=\"booksCategory\"><p onclick=\"window.open(\'../categories/fiction.html\',\'_parent\')\">Fiction</p><p onclick=\"window.open(\'../categories/nonfiction.html\',\'_parent\')\">Non-Fiction</p><p onclick=\"window.open(\'../categories/children.html\',\'_parent\')\">Children</p><p onclick=\"window.open(\'../categories/poetry.html\',\'_parent\')\">Poetry</p><p onclick=\"window.open(\'../categories/translation.html\',\'_parent\')\">Translations</p></div><p onclick=\"collapse(\'aboutCategory\')\" class=\"categoriesTitle\">About Us +</p><div id=\"aboutCategory\"><p>About us</p><p>Work with us</p><p>Publish with us</p></div><p onclick=\"collapse(\'artCategory\')\" class=\"categoriesTitle\">Arts and Craft +</p><div id=\"artCategory\"><p>Arts</p><p>Craft</p></div><p class=\"categoriesTitle\" onclick=\"window.open(\'../author.html\',\'_parent\')\">Authors</p><p class=\"categoriesTitle\" onclick=\"window.open(\'../poster.html\',\'_parent\')\">Poster Kavita</p><p class=\"categoriesTitle\" onclick=\"window.open(\'../blog.html\',\'_parent\')\">Blog</p><p class=\"categoriesTitle\" onclick=\"window.open(\'../account.html\',\'_parent\')\">Account</p>");
    }

}